version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    image: jaswanth434/sdcnginx:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
  client:
    image: jaswanth434/sdcclient:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    working_dir: /usr/app
  server:
    image: jaswanth434/sdcserver:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    working_dir: /usr/app
    depends_on:
      - postgres
      - redis
    
